heat_template_version: 2013-05-23

parameters:
  foo:
    type: string
  the_server:
    type: string
resources:
  custom_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: foo
      outputs:
      - name: result
      config: |
        echo $foo > /tmp/foo

  custom_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: HEAT_SIGNAL
      config:
        get_resource: custom_config
      server:
        get_param: the_server
      input_values:
        foo: { get_param: foo }

outputs:
  result:
    value: foobar
